train_path: dataset/captions_train2017.json
dev_path:  dataset/nocaps_val_captions.json
copy_vocab_path: dataset/new_object_class_v2.txt
train_obj_h5_path: dataset/train_adaptive_101.h5
dev_obj_h5_path: dataset/nocaps_val_adaptive.h5
train_copy_obj_h5_path: dataset/tf_faster_rcnn_inception_resnet_v2_atrous_oid_v4_boxes.h5
dev_copy_obj_h5_path: dataset/tf_faster_rcnn_inception_resnet_v2_atrous_oid_v4_boxes.h5
word_norm_jsonpath: dataset/word_norm.json
max_generation_len: 20
batch_size: 25
gradient_accumulation_steps: 2
learning_rate: 5e-5
checkpoint_every_step: 6000
max_epoch: 15
use_pointer: False
use_mention_flag: True
lm_type: t5-base
freeze_param: True
enable_visual: True
use_copy_obj: True
object_blacklist_path: dataset/blacklist_only_no_people.json
rm_dumplicated_caption: True
shuffle_data: True
external_eval: False
rm_punctuation: False
mention_flag_state: 4
relative_pos_num: 55
use_orginal_enc_pos_embs: True
freeze_enc_pos_param: False
static_mf: False
do_pretrain_lm_init: True
use_mf_scalar: False
