train_path: dataset/e2e_train_old.json
dev_path: dataset/e2e_dev_old.json
test_path: dataset/e2e_test_old.json
copy_vocab_path: dataset/new_copy_vocab_all.txt
max_generation_len: 50
batch_size: 50
gradient_accumulation_steps: 1
learning_rate: 5e-5
checkpoint_every_step: 1000
max_epoch: 15
use_pointer: False
use_mention_flag: True
mention_flag_state: 3
lm_type: t5-base
freeze_param: True
enable_visual: False
rm_dumplicated_caption: True
shuffle_data: True
rm_punctuation: False
relative_pos_num: 55
use_orginal_enc_pos_embs: True
freeze_enc_pos_param: False
do_pretrain_lm_init: True
